package com.itwn.cinema.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Film {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.fname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.releasedate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd")
    private Date releasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.releasecountry
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String releasecountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.type
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.country
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.language
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.duration
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.boxoffice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Long boxoffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.gradecount
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Long gradecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.score
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.director
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;
    private int recommend;
    private String filmimg;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.fid
     *
     * @return the value of t_film.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.fid
     *
     * @param fid the value for t_film.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.fname
     *
     * @return the value of t_film.fname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.fname
     *
     * @param fname the value for t_film.fname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.releasedate
     *
     * @return the value of t_film.releasedate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getReleasedate() {
        return releasedate;
    }

    public int getRecommend() {
        return recommend;
    }

    public void setRecommend(int recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.releasedate
     *
     * @param releasedate the value for t_film.releasedate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.releasecountry
     *
     * @return the value of t_film.releasecountry
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getReleasecountry() {
        return releasecountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.releasecountry
     *
     * @param releasecountry the value for t_film.releasecountry
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setReleasecountry(String releasecountry) {
        this.releasecountry = releasecountry == null ? null : releasecountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.type
     *
     * @return the value of t_film.type
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.type
     *
     * @param type the value for t_film.type
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.country
     *
     * @return the value of t_film.country
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.country
     *
     * @param country the value for t_film.country
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.language
     *
     * @return the value of t_film.language
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.language
     *
     * @param language the value for t_film.language
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.duration
     *
     * @return the value of t_film.duration
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.duration
     *
     * @param duration the value for t_film.duration
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.boxoffice
     *
     * @return the value of t_film.boxoffice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Long getBoxoffice() {
        return boxoffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.boxoffice
     *
     * @param boxoffice the value for t_film.boxoffice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setBoxoffice(Long boxoffice) {
        this.boxoffice = boxoffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.description
     *
     * @return the value of t_film.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.description
     *
     * @param description the value for t_film.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.gradecount
     *
     * @return the value of t_film.gradecount
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Long getGradecount() {
        return gradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.gradecount
     *
     * @param gradecount the value for t_film.gradecount
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setGradecount(Long gradecount) {
        this.gradecount = gradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.score
     *
     * @return the value of t_film.score
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.score
     *
     * @param score the value for t_film.score
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.director
     *
     * @return the value of t_film.director
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.director
     *
     * @param director the value for t_film.director
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.status
     *
     * @return the value of t_film.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.status
     *
     * @param status the value for t_film.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getFilmimg() {
        return filmimg;
    }

    public void setFilmimg(String filmimg) {
        this.filmimg = filmimg;
    }



}