package com.itwn.cinema.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class FilmComent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.cid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer fid;
    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.score
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.creaetedate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    @JsonFormat(pattern = "MM-dd")
    private Date creaetedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.stars
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmcoment.content
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.cid
     *
     * @return the value of t_filmcoment.cid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.cid
     *
     * @param cid the value for t_filmcoment.cid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.uid
     *
     * @return the value of t_filmcoment.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.uid
     *
     * @param uid the value for t_filmcoment.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.fid
     *
     * @return the value of t_filmcoment.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.fid
     *
     * @param fid the value for t_filmcoment.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.score
     *
     * @return the value of t_filmcoment.score
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.score
     *
     * @param score the value for t_filmcoment.score
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.creaetedate
     *
     * @return the value of t_filmcoment.creaetedate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getCreaetedate() {
        return creaetedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.creaetedate
     *
     * @param creaetedate the value for t_filmcoment.creaetedate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCreaetedate(Date creaetedate) {
        this.creaetedate = creaetedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.stars
     *
     * @return the value of t_filmcoment.stars
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.stars
     *
     * @param stars the value for t_filmcoment.stars
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.status
     *
     * @return the value of t_filmcoment.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.status
     *
     * @param status the value for t_filmcoment.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.description
     *
     * @return the value of t_filmcoment.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.description
     *
     * @param description the value for t_filmcoment.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmcoment.content
     *
     * @return the value of t_filmcoment.content
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmcoment.content
     *
     * @param content the value for t_filmcoment.content
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}