package com.itwn.cinema.pojo;

import lombok.Data;

import java.util.Date;
import java.util.List;
@Data
public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.oid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer sfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.createdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.serialnum
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String serialnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    public Orders(){}

    public Orders(Integer uid, Integer sfid, Date createdate, String serialnum, Integer status, String description) {
        this.uid = uid;
        this.sfid = sfid;
        this.createdate = createdate;
        this.serialnum = serialnum;
        this.status = status;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.oid
     *
     * @return the value of t_orders.oid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */



    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.oid
     *
     * @param oid the value for t_orders.oid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.uid
     *
     * @return the value of t_orders.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.uid
     *
     * @param uid the value for t_orders.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.sfid
     *
     * @return the value of t_orders.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSfid() {
        return sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.sfid
     *
     * @param sfid the value for t_orders.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSfid(Integer sfid) {
        this.sfid = sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.createdate
     *
     * @return the value of t_orders.createdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.createdate
     *
     * @param createdate the value for t_orders.createdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.serialnum
     *
     * @return the value of t_orders.serialnum
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getSerialnum() {
        return serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.serialnum
     *
     * @param serialnum the value for t_orders.serialnum
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSerialnum(String serialnum) {
        this.serialnum = serialnum == null ? null : serialnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.status
     *
     * @return the value of t_orders.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.status
     *
     * @param status the value for t_orders.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.description
     *
     * @return the value of t_orders.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.description
     *
     * @param description the value for t_orders.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}
