package com.shana.cinema.mapper;

import com.shana.cinema.pojo.Adevertisement;
import java.util.List;

public interface AdevertisementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(Adevertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    Adevertisement selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<Adevertisement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advertisement
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(Adevertisement record);
}