package com.shana.cinema.mapper;

import com.shana.cinema.pojo.CinemaBranch;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface CinemaBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cinema_branch
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer cdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cinema_branch
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(CinemaBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cinema_branch
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    CinemaBranch selectByPrimaryKey(Integer cdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cinema_branch
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<CinemaBranch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cinema_branch
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(CinemaBranch record);
    @Delete("delete from t_cinema_branch where cdid=#{cdid}")
    int delecteByCdid(Integer cdid);


    @Update("update t_cinema_branch set cdname=#{cdname},address=#{address},province=#{province},city=#{city},area=#{area},tel=#{tel},status=#{status},description=#{description} where cdid=#{cdid}")
    int updataBrand(CinemaBranch cinemaBranch);
    @Insert("insert into t_cinema_branch(cdname,address,province,city,area,coordinate,tel,status,description) values(#{cdname},#{address},#{province},#{city},#{area},#{coordinate},#{tel},#{status},#{description})")
    int insertbrand(CinemaBranch cinemaBranch);


    //删除影厅
    @Delete("delete from t_screens where cdid=#{cdid}")
    int deleteScreensBycdid(Integer cdid);
    //删除排片
    @Delete("delete from t_screen_film where sid in (select sid from t_screens where cdid=#{cdid})")
    int deleteScreenFilmByCdid(Integer cdid);
}
