package com.shana.cinema.mapper;

import com.shana.cinema.pojo.Orders;
import com.shana.cinema.pojo.QvOrder;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    Orders selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<Orders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(Orders record);

    //插入order数据同时返回id
    int insertorder(Orders order);

    //一定时间后查看当前订单状态
    @Select("select status from t_orders where oid=#{oid}")
    int selectstatusbyoid(int oid);

    //到时间未付款将订单状态改为2超时未付款状态
    @Update("update t_orders set status=2 where oid=#{oid}")
    void updatestatus(int oid);

    @Select("select * from showorder where oid=(select max(oid) from showorder) and uid=#{uid}")
    List<QvOrder> selectlastorder(int uid);

    @Update("update t_orders set status=1 where oid=#{oid}")
    void updatestatus1(int oid);
}