package com.shana.cinema.mapper;

import com.shana.cinema.pojo.Role;
import com.shana.cinema.pojo.Roles;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screens
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screens
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screens
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    Role selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screens
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screens
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(Role record);

    @Select("select * from t_role where status = 1")
    List<Roles> selectAllRole();
}