package com.shana.cinema.mapper;

import com.shana.cinema.pojo.ScreenSeats;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Component
public interface ScreenSeatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_seats
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_seats
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(ScreenSeats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_seats
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    ScreenSeats selectByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_seats
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<ScreenSeats> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_seats
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(ScreenSeats record);

    @Select(" select * from t_screen_seats where sfid=#{sfid}")
    List<ScreenSeats> selectBySfid(int sfid);

    @Select("select sfid from t_screen_seats where ssid=#{firstssid}")
     int selectsfidByssid(String firstssid);

   @Update("update t_screen_seats set status=3,notpaydate=#{createdate} where ssid=#{ssid}")
    void updateScreenSeats(String ssid, Date createdate);

    @Select("update t_screen_seats set status=1 where ssid=#{ssid}")
    void updateseatstatusbyssid(int ssid);
}