package com.shana.cinema.pojo;

import java.util.Date;

public class Adevertisement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.aid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.img
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.url
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.createdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.aid
     *
     * @return the value of t_advertisement.aid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.aid
     *
     * @param aid the value for t_advertisement.aid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.img
     *
     * @return the value of t_advertisement.img
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.img
     *
     * @param img the value for t_advertisement.img
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.url
     *
     * @return the value of t_advertisement.url
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.url
     *
     * @param url the value for t_advertisement.url
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.createdate
     *
     * @return the value of t_advertisement.createdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.createdate
     *
     * @param createdate the value for t_advertisement.createdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.status
     *
     * @return the value of t_advertisement.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.status
     *
     * @param status the value for t_advertisement.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.description
     *
     * @return the value of t_advertisement.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.description
     *
     * @param description the value for t_advertisement.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}