package com.shana.cinema.pojo;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.aid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.aname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String aname;
    private String img;

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.apass
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String apass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_administrator.descriptrion
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String descriptrion;
    private int age;
    private String gender;
    private String tel;
    private int rid;

    public int getRid() {
        return rid;
    }

    public void setRid(int rid) {
        this.rid = rid;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.aid
     *
     * @return the value of t_administrator.aid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.aid
     *
     * @param aid the value for t_administrator.aid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.aname
     *
     * @return the value of t_administrator.aname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.aname
     *
     * @param aname the value for t_administrator.aname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.apass
     *
     * @return the value of t_administrator.apass
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getApass() {
        return apass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.apass
     *
     * @param apass the value for t_administrator.apass
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setApass(String apass) {
        this.apass = apass == null ? null : apass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.status
     *
     * @return the value of t_administrator.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.status
     *
     * @param status the value for t_administrator.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_administrator.descriptrion
     *
     * @return the value of t_administrator.descriptrion
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescriptrion() {
        return descriptrion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_administrator.descriptrion
     *
     * @param descriptrion the value for t_administrator.descriptrion
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescriptrion(String descriptrion) {
        this.descriptrion = descriptrion == null ? null : descriptrion.trim();
    }
}