package com.shana.cinema.pojo;

public class CinemaBranch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.cdid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer cdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.cdname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String cdname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.address
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.province
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.city
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.area
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.coordinate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String coordinate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.tel
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cinema_branch.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.cdid
     *
     * @return the value of t_cinema_branch.cdid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getCdid() {
        return cdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.cdid
     *
     * @param cdid the value for t_cinema_branch.cdid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCdid(Integer cdid) {
        this.cdid = cdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.cdname
     *
     * @return the value of t_cinema_branch.cdname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getCdname() {
        return cdname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.cdname
     *
     * @param cdname the value for t_cinema_branch.cdname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCdname(String cdname) {
        this.cdname = cdname == null ? null : cdname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.address
     *
     * @return the value of t_cinema_branch.address
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.address
     *
     * @param address the value for t_cinema_branch.address
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.province
     *
     * @return the value of t_cinema_branch.province
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.province
     *
     * @param province the value for t_cinema_branch.province
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.city
     *
     * @return the value of t_cinema_branch.city
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.city
     *
     * @param city the value for t_cinema_branch.city
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.area
     *
     * @return the value of t_cinema_branch.area
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.area
     *
     * @param area the value for t_cinema_branch.area
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.coordinate
     *
     * @return the value of t_cinema_branch.coordinate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getCoordinate() {
        return coordinate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.coordinate
     *
     * @param coordinate the value for t_cinema_branch.coordinate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCoordinate(String coordinate) {
        this.coordinate = coordinate == null ? null : coordinate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.tel
     *
     * @return the value of t_cinema_branch.tel
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.tel
     *
     * @param tel the value for t_cinema_branch.tel
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.status
     *
     * @return the value of t_cinema_branch.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.status
     *
     * @param status the value for t_cinema_branch.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cinema_branch.description
     *
     * @return the value of t_cinema_branch.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cinema_branch.description
     *
     * @param description the value for t_cinema_branch.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}