package com.shana.cinema.pojo;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_details.odid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer odid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_details.oid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_details.ssid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer ssid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_details.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_details.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.odid
     *
     * @return the value of t_order_details.odid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getOdid() {
        return odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.odid
     *
     * @param odid the value for t_order_details.odid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setOdid(Integer odid) {
        this.odid = odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.oid
     *
     * @return the value of t_order_details.oid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.oid
     *
     * @param oid the value for t_order_details.oid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.ssid
     *
     * @return the value of t_order_details.ssid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.ssid
     *
     * @param ssid the value for t_order_details.ssid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSsid(Integer ssid) {
        this.ssid = ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.status
     *
     * @return the value of t_order_details.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.status
     *
     * @param status the value for t_order_details.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_details.description
     *
     * @return the value of t_order_details.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_details.description
     *
     * @param description the value for t_order_details.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}