package com.shana.cinema.pojo;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.sid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.sname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.cbid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String cbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.seatcount
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer seatcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.seatx
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer seatx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.seaty
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer seaty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.corridory
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer corridory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.category
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screens.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.sid
     *
     * @return the value of t_screens.sid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.sid
     *
     * @param sid the value for t_screens.sid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.sname
     *
     * @return the value of t_screens.sname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.sname
     *
     * @param sname the value for t_screens.sname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.cbid
     *
     * @return the value of t_screens.cbid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getCbid() {
        return cbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.cbid
     *
     * @param cbid the value for t_screens.cbid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCbid(String cbid) {
        this.cbid = cbid == null ? null : cbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.seatcount
     *
     * @return the value of t_screens.seatcount
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSeatcount() {
        return seatcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.seatcount
     *
     * @param seatcount the value for t_screens.seatcount
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSeatcount(Integer seatcount) {
        this.seatcount = seatcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.seatx
     *
     * @return the value of t_screens.seatx
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSeatx() {
        return seatx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.seatx
     *
     * @param seatx the value for t_screens.seatx
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSeatx(Integer seatx) {
        this.seatx = seatx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.seaty
     *
     * @return the value of t_screens.seaty
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSeaty() {
        return seaty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.seaty
     *
     * @param seaty the value for t_screens.seaty
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSeaty(Integer seaty) {
        this.seaty = seaty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.corridory
     *
     * @return the value of t_screens.corridory
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getCorridory() {
        return corridory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.corridory
     *
     * @param corridory the value for t_screens.corridory
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCorridory(Integer corridory) {
        this.corridory = corridory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.category
     *
     * @return the value of t_screens.category
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.category
     *
     * @param category the value for t_screens.category
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.status
     *
     * @return the value of t_screens.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.status
     *
     * @param status the value for t_screens.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screens.description
     *
     * @return the value of t_screens.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screens.description
     *
     * @param description the value for t_screens.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}