package com.shana.cinema.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class ScreenFilm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer sfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.sid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.price
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.nowprice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Double nowprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.showtime
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    @DateTimeFormat(pattern = "HH点mm分")
    @JsonFormat(pattern = "HH点mm分",timezone = "GMT+8")
    private Date showtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.endtime
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    @DateTimeFormat(pattern = "HH点mm分")
    @JsonFormat(pattern = "HH点mm分",timezone = "GMT+8")
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_film.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    private Date scheduledate;

    public Date getScheduledate() {
        return scheduledate;
    }

    public void setScheduledate(Date scheduledate) {
        this.scheduledate = scheduledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.sfid
     *
     * @return the value of t_screen_film.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSfid() {
        return sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.sfid
     *
     * @param sfid the value for t_screen_film.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSfid(Integer sfid) {
        this.sfid = sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.fid
     *
     * @return the value of t_screen_film.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.fid
     *
     * @param fid the value for t_screen_film.fid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.sid
     *
     * @return the value of t_screen_film.sid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.sid
     *
     * @param sid the value for t_screen_film.sid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.price
     *
     * @return the value of t_screen_film.price
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.price
     *
     * @param price the value for t_screen_film.price
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.nowprice
     *
     * @return the value of t_screen_film.nowprice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Double getNowprice() {
        return nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.nowprice
     *
     * @param nowprice the value for t_screen_film.nowprice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setNowprice(Double nowprice) {
        this.nowprice = nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.showtime
     *
     * @return the value of t_screen_film.showtime
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getShowtime() {
        return showtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.showtime
     *
     * @param showtime the value for t_screen_film.showtime
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setShowtime(Date showtime) {
        this.showtime = showtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.endtime
     *
     * @return the value of t_screen_film.endtime
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.endtime
     *
     * @param endtime the value for t_screen_film.endtime
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.status
     *
     * @return the value of t_screen_film.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.status
     *
     * @param status the value for t_screen_film.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_film.description
     *
     * @return the value of t_screen_film.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_film.description
     *
     * @param description the value for t_screen_film.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        return "ScreenFilm{" +
                "sfid=" + sfid +
                ", fid=" + fid +
                ", sid=" + sid +
                ", price=" + price +
                ", nowprice=" + nowprice +
                ", showtime=" + showtime +
                ", endtime=" + endtime +
                ", status=" + status +
                ", description='" + description + '\'' +
                ", scheduledate=" + scheduledate +
                '}';
    }
}