package com.shana.cinema.pojo;

import java.util.Date;

public class ScreenSeats {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_seats.ssid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer ssid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_seats.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer sfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_seats.x
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_seats.y
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_seats.nowprice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Double nowprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_seats.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;
    private Date notpaydate;

    public Date getNotpaydate() {
        return notpaydate;
    }

    public void setNotpaydate(Date notpaydate) {
        this.notpaydate = notpaydate;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_seats.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_seats.ssid
     *
     * @return the value of t_screen_seats.ssid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_seats.ssid
     *
     * @param ssid the value for t_screen_seats.ssid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSsid(Integer ssid) {
        this.ssid = ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_seats.sfid
     *
     * @return the value of t_screen_seats.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getSfid() {
        return sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_seats.sfid
     *
     * @param sfid the value for t_screen_seats.sfid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setSfid(Integer sfid) {
        this.sfid = sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_seats.x
     *
     * @return the value of t_screen_seats.x
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_seats.x
     *
     * @param x the value for t_screen_seats.x
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_seats.y
     *
     * @return the value of t_screen_seats.y
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_seats.y
     *
     * @param y the value for t_screen_seats.y
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_seats.nowprice
     *
     * @return the value of t_screen_seats.nowprice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Double getNowprice() {
        return nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_seats.nowprice
     *
     * @param nowprice the value for t_screen_seats.nowprice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setNowprice(Double nowprice) {
        this.nowprice = nowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_seats.status
     *
     * @return the value of t_screen_seats.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_seats.status
     *
     * @param status the value for t_screen_seats.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_seats.description
     *
     * @return the value of t_screen_seats.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_seats.description
     *
     * @param description the value for t_screen_seats.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}