package com.shana.cinema.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.upass
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String upass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.gender
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.img
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.tel
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.vip
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer vip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.vipdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date vipdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.vipenddate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date vipenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.integral
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uid
     *
     * @return the value of t_user.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uid
     *
     * @param uid the value for t_user.uid
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uname
     *
     * @return the value of t_user.uname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uname
     *
     * @param uname the value for t_user.uname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.upass
     *
     * @return the value of t_user.upass
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.upass
     *
     * @param upass the value for t_user.upass
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setUpass(String upass) {
        this.upass = upass == null ? null : upass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.img
     *
     * @return the value of t_user.img
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.img
     *
     * @param img the value for t_user.img
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.tel
     *
     * @return the value of t_user.tel
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.tel
     *
     * @param tel the value for t_user.tel
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.vip
     *
     * @return the value of t_user.vip
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.vip
     *
     * @param vip the value for t_user.vip
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.vipdate
     *
     * @return the value of t_user.vipdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getVipdate() {
        return vipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.vipdate
     *
     * @param vipdate the value for t_user.vipdate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setVipdate(Date vipdate) {
        this.vipdate = vipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.vipenddate
     *
     * @return the value of t_user.vipenddate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Date getVipenddate() {
        return vipenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.vipenddate
     *
     * @param vipenddate the value for t_user.vipenddate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setVipenddate(Date vipenddate) {
        this.vipenddate = vipenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.integral
     *
     * @return the value of t_user.integral
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.integral
     *
     * @param integral the value for t_user.integral
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}