package com.itwn.cinema.response;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.itwn.cinema.pojo.Film;
import com.itwn.cinema.pojo.Screens;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 功能描述:<br>
 * 〈〉
 *
 * @author EDZ
 * @create 2019/10/24
 * @since 1.0.0
 */
@Data
public class FilmScreen01 {
    private int sid;
    private String sname;
    private int cbid;
    private int seatcount;
    private int seatx;
    private int seaty;
    private int corridory;
    private String category;
    private int status;
    private String description;
    private int sfid;
    private Film film;
    private Screens screens;
    private double price;
    private double nowprice;
    private Date showtime;
    private String show;
    private Date endtime;
    private String end;
    private Date scheduledate;
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.fname
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.releasedate
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd")
    private Date releasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.releasecountry
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String releasecountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.type
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.country
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.language
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.duration
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.boxoffice
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Long boxoffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.description
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.gradecount
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Long gradecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.score
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.director
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_film.status
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    private int recommend;
    private String filmimg;
}
