package com.itwn.cinema.mapper;

import com.itwn.cinema.pojo.Administrator;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    Administrator selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<Administrator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_administrator
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(Administrator record);

    @Select(" select * from t_administrator where aname=#{aname} and apass=#{apass} ")
    Administrator selectByUnameAndUpass(Administrator administrator);

    @Update("update t_administrator set status = #{status}, rid = #{rid} where aid = #{aid}")
    void updateById(Administrator admin);

    @Select(" select * from t_administrator where aname=#{aname}")
    Administrator selectByAname(String aname);
}