package com.itwn.cinema.mapper;

import com.itwn.cinema.pojo.FilmComent;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface FilmComentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_filmcoment
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_filmcoment
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(FilmComent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_filmcoment
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    FilmComent selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_filmcoment
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<FilmComent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_filmcoment
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(FilmComent record);

    List<FilmComent> selectByFilmId(int fid);
}