package com.itwn.cinema.mapper;

import com.itwn.cinema.pojo.ScreenFilm;
import com.itwn.cinema.response.FilmScreen01;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ScreenFilmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_film
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int deleteByPrimaryKey(Integer sfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_film
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int insert(ScreenFilm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_film
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    ScreenFilm selectByPrimaryKey(Integer sfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_film
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    List<ScreenFilm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_film
     *
     * @mbg.generated Fri Oct 18 15:15:43 CST 2019
     */
    int updateByPrimaryKey(ScreenFilm record);

    @Select("select * from t_screen_film where scheduledate >= #{scheduledate} and sid = #{sid}")
    List<ScreenFilm> selectScreenFilmByScreenAndTime(ScreenFilm sf);

    @Select(" select * from t_screen_film where fid=#{fid}")
    List<ScreenFilm> selectScreenFilmByFid(int fid);

    List<FilmScreen01> selectScreenFilmByFidAndSid(int fid, int cbid);

    @Select(" select * from t_screen_film where sfid=#{sfid}")
    ScreenFilm selectBySfid(int sfid);

    @Select(" select * from t_screen_film where sid=#{sid}")
    List<ScreenFilm> selectBySid(int sid);

    List<FilmScreen01> selectScreenFilmByCbid(int cbid);
}